import React, { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { Card, Descriptions, Button, Space, Spin, Typography, Tag, Divider, Image } from 'antd';
import axios from 'axios';

const { Title, Text } = Typography;

const ReportDetail = () => {
  const [report, setReport] = useState(null);
  const [loading, setLoading] = useState(true);
  const { id } = useParams();
  const navigate = useNavigate();

  const fetchReportDetails = React.useCallback(async () => {
    try {
      const token = localStorage.getItem('wku_cms_token');
      const response = await axios.get(`/api/reports/${id}`, {
        headers: {
          'Authorization': `Bearer ${token}`
        }
      });
      setReport(response.data.data);
      setLoading(false);
    } catch (error) {
      console.error('Error fetching report details:', error);
      setLoading(false);
    }
  }, [id]);

  useEffect(() => {
    fetchReportDetails();
  }, [fetchReportDetails]);

  if (loading) {
    return (
      <div className="flex justify-center items-center h-full">
        <Spin size="large" />
      </div>
    );
  }

  if (!report) {
    return (
      <div className="text-center">
        <Title level={3}>Report not found</Title>
        <Button type="primary" onClick={() => navigate('/committee-reports')}>
          Back to Reports
        </Button>
      </div>
    );
  }

  return (
    <div className="p-6">
      <Card>
        <div className="flex justify-between items-center mb-6">
          <Title level={2}>{report.title}</Title>
          <Space>
            <Button onClick={() => navigate('/committee-reports')}>
              Back to Reports
            </Button>
          </Space>
        </div>

        <Descriptions bordered column={2}>
          <Descriptions.Item label="Project">
            {report.project?.projectName}
          </Descriptions.Item>
          <Descriptions.Item label="Type">
            {report.type}
          </Descriptions.Item>
          <Descriptions.Item label="Status">
            <Tag color={report.status === 'approved' ? 'green' : report.status === 'pending' ? 'orange' : 'red'}>
              {report.status?.toUpperCase()}
            </Tag>
          </Descriptions.Item>
          <Descriptions.Item label="Generated By">
            {`${report.generatedBy?.firstName || ''} ${report.generatedBy?.lastName || ''}`}
          </Descriptions.Item>
          <Descriptions.Item label="Created Date">
            {new Date(report.createdAt).toLocaleDateString()}
          </Descriptions.Item>
          <Descriptions.Item label="Summary" span={2}>
            {report.summary}
          </Descriptions.Item>
          {report.issuesAndRisks && report.issuesAndRisks.length > 0 && (
            <Descriptions.Item label="Issues and Risks" span={2}>
              <ul>
                {report.issuesAndRisks.map((issue, index) => (
                  <li key={issue._id || index}>
                    <Tag color={issue.severity === 'high' ? 'red' : 'orange'}>{issue.severity}</Tag>
                    {' '}{issue.description}
                  </li>
                ))}
              </ul>
            </Descriptions.Item>
          )}
        </Descriptions>

        <Divider />

        <div className="mt-6">
          <Title level={4}>Attachments</Title>
          {report.attachments?.length > 0 ? (
            <Space direction="vertical" className="w-full">
              {report.attachments.map((attachment, index) => (
                <Card key={attachment._id || index} size="small">
                  <div className="flex justify-between items-center">
                    <Text>{attachment.fileName}</Text>
                    <Button type="link" href={attachment.url} target="_blank">
                      Download
                    </Button>
                  </div>
                </Card>
              ))}
            </Space>
          ) : (
            <Text>No attachments available</Text>
          )}
        </div>
      </Card>
    </div>
  );
};

export default ReportDetail;